brew:
  taps:
    romkatv/powerlevel10k: true
    homeport/tap: true
  packages:
    hugo: true
    docker-credential-helper: true
    jq: true
    colima: false
    wget: true
    rename: true
    git: true
    ripgrep: true
    helm: true
    kind: true
    pgrep: true
    kubie: false
    gron: true
    fx: true
    eza: true
    bat: true
    fzf: true
    neovim: true
    direnv: true
    k9s: true
    stern: true
    docker: true
    dyff: true
    tree: true
    the_silver_searcher: true
kubectl:
  enabled: true
  krew:
    enabled: true
    plugins:
      stern: true
      view-secret: true
      explore: true
      tree: true
      foreach: true
      neat: true
vscode:
  enabled: true
zsh:
  theme: spaceship
  plugins:
  - name: git
  - name: sudo
  - name: copybuffer
  - name: kubectl
  - name: fzf
  - name: zsh-autosuggestions
    source: github.com/zsh-users/zsh-autosuggestions
  - name: zsh-syntax-highlighting
    source: github.com/zsh-users/zsh-syntax-highlighting
hooks:
- scripts/create-bin-dir
- scripts/install-tpm
