#!/usr/bin/env bash

set -e
set -u
set -o pipefail

tpm_dir=~/.tmux/plugins/tpm

if [[ ! -d "$tpm_dir" ]]; then
  git clone https://github.com/tmux-plugins/tpm $tpm_dir --depth=1
fi

cd $tpm_dir
git pull
