#!/usr/bin/env bash

download_dir=$(mktemp -d)

cd $download_dir

curl -o bw.zip -JL https://vault.bitwarden.com/download/\?app\=cli\&platform\=macos

unzip bw.zip 

mv bw $HOME/bin 

rm -rf $download_dir